import "server-only";

import {
  parseNativeOkfAccessConfig,
  type NativeOkfAccessConfig,
} from "./config.ts";

type EnvironmentSource = Readonly<Record<string, string | undefined>>;

/**
 * Projects only named access, quota, and pricing settings. It deliberately
 * never reads or enumerates API credentials or the complete environment.
 */
export function projectNativeOkfAccessEnvironment(
  source: EnvironmentSource,
): Record<string, string | undefined> {
  return {
    NODE_ENV: source.NODE_ENV,
    NATIVE_OKF_CHAT_ENABLED: source.NATIVE_OKF_CHAT_ENABLED,
    NATIVE_OKF_ACCESS_MODE: source.NATIVE_OKF_ACCESS_MODE,
    NATIVE_OKF_SESSION_SECRET: source.NATIVE_OKF_SESSION_SECRET,
    NATIVE_OKF_INVITE_HASH_SECRET: source.NATIVE_OKF_INVITE_HASH_SECRET,
    NATIVE_OKF_TEST_ACCESS_CODE: source.NATIVE_OKF_TEST_ACCESS_CODE,
    NATIVE_OKF_ADMIN_ACCESS_CODE: source.NATIVE_OKF_ADMIN_ACCESS_CODE,
    NATIVE_OKF_ADMIN_SESSION_SECRET: source.NATIVE_OKF_ADMIN_SESSION_SECRET,
    NATIVE_OKF_USAGE_DB_PATH: source.NATIVE_OKF_USAGE_DB_PATH,
    NATIVE_OKF_TEST_DAILY_QUESTIONS:
      source.NATIVE_OKF_TEST_DAILY_QUESTIONS,
    NATIVE_OKF_TEST_DAILY_DIAGRAMS:
      source.NATIVE_OKF_TEST_DAILY_DIAGRAMS,
    NATIVE_OKF_TEST_TOTAL_QUESTIONS:
      source.NATIVE_OKF_TEST_TOTAL_QUESTIONS,
    NATIVE_OKF_TEST_TOTAL_DIAGRAMS:
      source.NATIVE_OKF_TEST_TOTAL_DIAGRAMS,
    NATIVE_OKF_INVITE_DEFAULT_VALID_DAYS:
      source.NATIVE_OKF_INVITE_DEFAULT_VALID_DAYS,
    NATIVE_OKF_INVITE_DAILY_QUESTIONS:
      source.NATIVE_OKF_INVITE_DAILY_QUESTIONS,
    NATIVE_OKF_INVITE_DAILY_DIAGRAMS:
      source.NATIVE_OKF_INVITE_DAILY_DIAGRAMS,
    NATIVE_OKF_INVITE_TOTAL_QUESTIONS:
      source.NATIVE_OKF_INVITE_TOTAL_QUESTIONS,
    NATIVE_OKF_INVITE_TOTAL_DIAGRAMS:
      source.NATIVE_OKF_INVITE_TOTAL_DIAGRAMS,
    NATIVE_OKF_PER_INVITE_RPM: source.NATIVE_OKF_PER_INVITE_RPM,
    NATIVE_OKF_GLOBAL_RPM: source.NATIVE_OKF_GLOBAL_RPM,
    NATIVE_OKF_IP_REQUESTS_PER_HOUR:
      source.NATIVE_OKF_IP_REQUESTS_PER_HOUR,
    NATIVE_OKF_REQUEST_COOLDOWN_SECONDS:
      source.NATIVE_OKF_REQUEST_COOLDOWN_SECONDS,
    NATIVE_OKF_MAX_CONCURRENT_PER_INVITE:
      source.NATIVE_OKF_MAX_CONCURRENT_PER_INVITE,
    NATIVE_OKF_MAX_GLOBAL_CONCURRENT:
      source.NATIVE_OKF_MAX_GLOBAL_CONCURRENT,
    NATIVE_OKF_HARD_DAILY_USD: source.NATIVE_OKF_HARD_DAILY_USD,
    NATIVE_OKF_HARD_MONTHLY_USD: source.NATIVE_OKF_HARD_MONTHLY_USD,
    NATIVE_OKF_TEST_HARD_DAILY_USD:
      source.NATIVE_OKF_TEST_HARD_DAILY_USD,
    NATIVE_OKF_TEST_HARD_MONTHLY_USD:
      source.NATIVE_OKF_TEST_HARD_MONTHLY_USD,
    NATIVE_OKF_RESEARCHER_SESSION_HOURS:
      source.NATIVE_OKF_RESEARCHER_SESSION_HOURS,
    NATIVE_OKF_ADMIN_SESSION_MINUTES:
      source.NATIVE_OKF_ADMIN_SESSION_MINUTES,
    NATIVE_OKF_TEXT_REQUEST_RESERVE_USD:
      source.NATIVE_OKF_TEXT_REQUEST_RESERVE_USD,
    NATIVE_OKF_DIAGRAM_REQUEST_RESERVE_USD:
      source.NATIVE_OKF_DIAGRAM_REQUEST_RESERVE_USD,
    NATIVE_OKF_RESERVATION_TTL_SECONDS:
      source.NATIVE_OKF_RESERVATION_TTL_SECONDS,
    NATIVE_OKF_ADMIN_MUTATIONS_PER_MINUTE:
      source.NATIVE_OKF_ADMIN_MUTATIONS_PER_MINUTE,
    NATIVE_OKF_TRUST_PROXY: source.NATIVE_OKF_TRUST_PROXY,
    NATIVE_OKF_TRUSTED_PROXY_HEADER:
      source.NATIVE_OKF_TRUSTED_PROXY_HEADER,
    NATIVE_OKF_TRUSTED_PROXY_HOPS:
      source.NATIVE_OKF_TRUSTED_PROXY_HOPS,
    NATIVE_OKF_PUBLIC_ORIGIN: source.NATIVE_OKF_PUBLIC_ORIGIN,
    OPENAI_INPUT_USD_PER_MILLION:
      source.OPENAI_INPUT_USD_PER_MILLION,
    OPENAI_CACHED_INPUT_USD_PER_MILLION:
      source.OPENAI_CACHED_INPUT_USD_PER_MILLION,
    OPENAI_OUTPUT_USD_PER_MILLION:
      source.OPENAI_OUTPUT_USD_PER_MILLION,
  };
}

export function readNativeOkfAccessRuntimeConfig(): NativeOkfAccessConfig {
  return parseNativeOkfAccessConfig(
    projectNativeOkfAccessEnvironment({
      NODE_ENV: process.env.NODE_ENV,
      NATIVE_OKF_CHAT_ENABLED: process.env.NATIVE_OKF_CHAT_ENABLED,
      NATIVE_OKF_ACCESS_MODE: process.env.NATIVE_OKF_ACCESS_MODE,
      NATIVE_OKF_SESSION_SECRET: process.env.NATIVE_OKF_SESSION_SECRET,
      NATIVE_OKF_INVITE_HASH_SECRET:
        process.env.NATIVE_OKF_INVITE_HASH_SECRET,
      NATIVE_OKF_TEST_ACCESS_CODE: process.env.NATIVE_OKF_TEST_ACCESS_CODE,
      NATIVE_OKF_ADMIN_ACCESS_CODE:
        process.env.NATIVE_OKF_ADMIN_ACCESS_CODE,
      NATIVE_OKF_ADMIN_SESSION_SECRET:
        process.env.NATIVE_OKF_ADMIN_SESSION_SECRET,
      NATIVE_OKF_USAGE_DB_PATH: process.env.NATIVE_OKF_USAGE_DB_PATH,
      NATIVE_OKF_TEST_DAILY_QUESTIONS:
        process.env.NATIVE_OKF_TEST_DAILY_QUESTIONS,
      NATIVE_OKF_TEST_DAILY_DIAGRAMS:
        process.env.NATIVE_OKF_TEST_DAILY_DIAGRAMS,
      NATIVE_OKF_TEST_TOTAL_QUESTIONS:
        process.env.NATIVE_OKF_TEST_TOTAL_QUESTIONS,
      NATIVE_OKF_TEST_TOTAL_DIAGRAMS:
        process.env.NATIVE_OKF_TEST_TOTAL_DIAGRAMS,
      NATIVE_OKF_INVITE_DEFAULT_VALID_DAYS:
        process.env.NATIVE_OKF_INVITE_DEFAULT_VALID_DAYS,
      NATIVE_OKF_INVITE_DAILY_QUESTIONS:
        process.env.NATIVE_OKF_INVITE_DAILY_QUESTIONS,
      NATIVE_OKF_INVITE_DAILY_DIAGRAMS:
        process.env.NATIVE_OKF_INVITE_DAILY_DIAGRAMS,
      NATIVE_OKF_INVITE_TOTAL_QUESTIONS:
        process.env.NATIVE_OKF_INVITE_TOTAL_QUESTIONS,
      NATIVE_OKF_INVITE_TOTAL_DIAGRAMS:
        process.env.NATIVE_OKF_INVITE_TOTAL_DIAGRAMS,
      NATIVE_OKF_PER_INVITE_RPM:
        process.env.NATIVE_OKF_PER_INVITE_RPM,
      NATIVE_OKF_GLOBAL_RPM: process.env.NATIVE_OKF_GLOBAL_RPM,
      NATIVE_OKF_IP_REQUESTS_PER_HOUR:
        process.env.NATIVE_OKF_IP_REQUESTS_PER_HOUR,
      NATIVE_OKF_REQUEST_COOLDOWN_SECONDS:
        process.env.NATIVE_OKF_REQUEST_COOLDOWN_SECONDS,
      NATIVE_OKF_MAX_CONCURRENT_PER_INVITE:
        process.env.NATIVE_OKF_MAX_CONCURRENT_PER_INVITE,
      NATIVE_OKF_MAX_GLOBAL_CONCURRENT:
        process.env.NATIVE_OKF_MAX_GLOBAL_CONCURRENT,
      NATIVE_OKF_HARD_DAILY_USD:
        process.env.NATIVE_OKF_HARD_DAILY_USD,
      NATIVE_OKF_HARD_MONTHLY_USD:
        process.env.NATIVE_OKF_HARD_MONTHLY_USD,
      NATIVE_OKF_TEST_HARD_DAILY_USD:
        process.env.NATIVE_OKF_TEST_HARD_DAILY_USD,
      NATIVE_OKF_TEST_HARD_MONTHLY_USD:
        process.env.NATIVE_OKF_TEST_HARD_MONTHLY_USD,
      NATIVE_OKF_RESEARCHER_SESSION_HOURS:
        process.env.NATIVE_OKF_RESEARCHER_SESSION_HOURS,
      NATIVE_OKF_ADMIN_SESSION_MINUTES:
        process.env.NATIVE_OKF_ADMIN_SESSION_MINUTES,
      NATIVE_OKF_TEXT_REQUEST_RESERVE_USD:
        process.env.NATIVE_OKF_TEXT_REQUEST_RESERVE_USD,
      NATIVE_OKF_DIAGRAM_REQUEST_RESERVE_USD:
        process.env.NATIVE_OKF_DIAGRAM_REQUEST_RESERVE_USD,
      NATIVE_OKF_RESERVATION_TTL_SECONDS:
        process.env.NATIVE_OKF_RESERVATION_TTL_SECONDS,
      NATIVE_OKF_ADMIN_MUTATIONS_PER_MINUTE:
        process.env.NATIVE_OKF_ADMIN_MUTATIONS_PER_MINUTE,
      NATIVE_OKF_TRUST_PROXY: process.env.NATIVE_OKF_TRUST_PROXY,
      NATIVE_OKF_TRUSTED_PROXY_HEADER:
        process.env.NATIVE_OKF_TRUSTED_PROXY_HEADER,
      NATIVE_OKF_TRUSTED_PROXY_HOPS:
        process.env.NATIVE_OKF_TRUSTED_PROXY_HOPS,
      NATIVE_OKF_PUBLIC_ORIGIN:
        process.env.NATIVE_OKF_PUBLIC_ORIGIN,
      OPENAI_INPUT_USD_PER_MILLION:
        process.env.OPENAI_INPUT_USD_PER_MILLION,
      OPENAI_CACHED_INPUT_USD_PER_MILLION:
        process.env.OPENAI_CACHED_INPUT_USD_PER_MILLION,
      OPENAI_OUTPUT_USD_PER_MILLION:
        process.env.OPENAI_OUTPUT_USD_PER_MILLION,
    }),
  );
}
